### ISSUE TITLE
Update to work with CS2

### ISSUE THREAD

**Issue by Max7cd** [sam-ai56/gsi-csgo#1]
CS2 slightly changed which fields are present in the requests.
This breaks the current implementation, because there are some fields missing.

**Comment by Max7cd** [comment]
#2 is one proposed way to fix this issue for cs2.

**Comment by Max7cd** [comment]
Are there better ways to fix this?
Using Option<u8> means that we break all implementations that depend on the fields being u8.
Which means we need to update to a new major version.
Another possibility might be replacing missing fields with 0 during parsing, which might be a better idea.

**Comment by sam-ai56** [comment]
Yes, it is possible to use `#[serde(default)]` for fields, then they would have 0 even if such a field does not exist.
But I think Valve removed some fields in the payload for cs2. And it would be better to remove them.

**Comment by sam-ai56** [comment]
And there are many such errors with Option in my library. My bad.

**Comment by sam-ai56** [comment]
Sorry I can't accept the commit. I wanted to archive this repository. I'd probably rather make a fork for cs2. Because I'm sure that Valve didn't change the gsi significantly, but some fields have definitely changed. And I'll fix the mistakes with Options.
